"""comparison consistency review decisions

Revision ID: 264848d03e0a
Revises: 377b604b1bf6
Create Date: 2026-09-23 20:56:25.252410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '264848d03e0a'
down_revision: Union[str, Sequence[str], None] = '377b604b1bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consistency_runs',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('runs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('comparison', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.Column('major_differences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['onboarding_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consistency_runs_plan_id'), 'consistency_runs', ['plan_id'], unique=False)
    op.create_table('comparison_reports',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('validation_result_id', sa.UUID(), nullable=True),
    sa.Column('rows', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['onboarding_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validation_result_id'], ['validation_results.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparison_reports_plan_id'), 'comparison_reports', ['plan_id'], unique=False)
    op.create_table('review_decisions',
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('original_finding', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('original_item', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('edited_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outcome', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['validation_findings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['onboarding_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_decisions_finding_id'), 'review_decisions', ['finding_id'], unique=False)
    op.create_index(op.f('ix_review_decisions_plan_id'), 'review_decisions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_review_decisions_reviewer_id'), 'review_decisions', ['reviewer_id'], unique=False)
    # Append-only at the database level, like audit_log.
    op.execute("""
        CREATE OR REPLACE FUNCTION review_decisions_append_only() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'review_decisions is append-only: % is not allowed', TG_OP;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_review_decisions_append_only
        BEFORE UPDATE OR DELETE ON review_decisions
        FOR EACH ROW EXECUTE FUNCTION review_decisions_append_only();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_decisions_reviewer_id'), table_name='review_decisions')
    op.drop_index(op.f('ix_review_decisions_plan_id'), table_name='review_decisions')
    op.drop_index(op.f('ix_review_decisions_finding_id'), table_name='review_decisions')
    op.execute("DROP TRIGGER IF EXISTS trg_review_decisions_append_only ON review_decisions")
    op.execute("DROP FUNCTION IF EXISTS review_decisions_append_only()")
    op.drop_table('review_decisions')
    op.drop_index(op.f('ix_comparison_reports_plan_id'), table_name='comparison_reports')
    op.drop_table('comparison_reports')
    op.drop_index(op.f('ix_consistency_runs_plan_id'), table_name='consistency_runs')
    op.drop_table('consistency_runs')
    # ### end Alembic commands ###
