"""requirements role matrix prerequisites audit log

Revision ID: 4ee676b42845
Revises: 521602c9b3ae
Create Date: 2026-09-23 17:06:35.854150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ee676b42845'
down_revision: Union[str, Sequence[str], None] = '521602c9b3ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    # Append-only, enforced by the database as well as the ORM.
    op.execute("""
        CREATE OR REPLACE FUNCTION audit_log_append_only() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit_log is append-only: % is not allowed', TG_OP;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_audit_log_append_only
        BEFORE UPDATE OR DELETE ON audit_log
        FOR EACH ROW EXECUTE FUNCTION audit_log_append_only();
    """)
    op.create_table('requirements',
    sa.Column('requirement_code', sa.String(length=20), nullable=False),
    sa.Column('source_key', sa.String(length=200), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('requirement_type', sa.Enum('MUST_KNOW', 'MUST_COMPLETE', 'MUST_DEMONSTRATE', 'MUST_ACKNOWLEDGE', 'RECOMMENDED', 'OPTIONAL', 'NOT_APPLICABLE', name='requirement_type'), nullable=False),
    sa.Column('competency', sa.String(length=150), nullable=False),
    sa.Column('policy_requirement', sa.Text(), nullable=True),
    sa.Column('process_requirement', sa.Text(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='priority'), nullable=False),
    sa.Column('is_compliance', sa.Boolean(), nullable=False),
    sa.Column('deadline_days', sa.Integer(), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('source_document_code', sa.String(length=60), nullable=False),
    sa.Column('source_chunk_id', sa.UUID(), nullable=True),
    sa.Column('source_chunk_code', sa.String(length=60), nullable=True),
    sa.Column('source_section_id', sa.String(length=40), nullable=True),
    sa.Column('assessment_required', sa.Boolean(), nullable=False),
    sa.Column('assessment_topic', sa.String(length=255), nullable=True),
    sa.Column('applies_to_all_roles', sa.Boolean(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('extraction_method', sa.String(length=200), nullable=False),
    sa.Column('manually_overridden', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['document_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirements_is_active'), 'requirements', ['is_active'], unique=False)
    op.create_index(op.f('ix_requirements_requirement_code'), 'requirements', ['requirement_code'], unique=True)
    op.create_index(op.f('ix_requirements_source_document_code'), 'requirements', ['source_document_code'], unique=False)
    op.create_index(op.f('ix_requirements_source_document_id'), 'requirements', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_requirements_source_key'), 'requirements', ['source_key'], unique=True)
    op.create_index(op.f('ix_requirements_source_section_id'), 'requirements', ['source_section_id'], unique=False)
    op.create_table('prerequisites',
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_requirement_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=60), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('requirement_id <> depends_on_requirement_id', name='ck_no_self_prerequisite'),
    sa.ForeignKeyConstraint(['depends_on_requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_id', 'depends_on_requirement_id', name='uq_prerequisite')
    )
    op.create_index(op.f('ix_prerequisites_depends_on_requirement_id'), 'prerequisites', ['depends_on_requirement_id'], unique=False)
    op.create_index(op.f('ix_prerequisites_requirement_id'), 'prerequisites', ['requirement_id'], unique=False)
    op.create_table('role_requirements',
    sa.Column('job_role_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('is_mandatory_for_role', sa.Boolean(), nullable=False),
    sa.Column('priority_for_role', postgresql.ENUM('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='priority', create_type=False), nullable=False),
    sa.Column('mapping_reason', sa.Text(), nullable=False),
    sa.Column('mapping_method', sa.Enum('EXPLICIT_ROLE_MENTION', 'DEPARTMENT_MATCH', 'APPLIES_TO_ALL', 'MANUAL', name='mapping_method'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_role_id', 'requirement_id', name='uq_role_requirement')
    )
    op.create_index(op.f('ix_role_requirements_job_role_id'), 'role_requirements', ['job_role_id'], unique=False)
    op.create_index(op.f('ix_role_requirements_requirement_id'), 'role_requirements', ['requirement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_requirements_requirement_id'), table_name='role_requirements')
    op.drop_index(op.f('ix_role_requirements_job_role_id'), table_name='role_requirements')
    op.drop_table('role_requirements')
    op.drop_index(op.f('ix_prerequisites_requirement_id'), table_name='prerequisites')
    op.drop_index(op.f('ix_prerequisites_depends_on_requirement_id'), table_name='prerequisites')
    op.drop_table('prerequisites')
    op.drop_index(op.f('ix_requirements_source_section_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_source_key'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_source_document_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_source_document_code'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_requirement_code'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_is_active'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.execute("DROP TRIGGER IF EXISTS trg_audit_log_append_only ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS audit_log_append_only()")
    op.drop_table('audit_log')
    for enum_name in ("mapping_method", "priority", "requirement_type"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    # ### end Alembic commands ###
