"""genai pipeline plans prompt templates generation runs

Revision ID: 577603a5644a
Revises: 4ee676b42845
Create Date: 2026-09-23 17:37:57.273909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '577603a5644a'
down_revision: Union[str, Sequence[str], None] = '4ee676b42845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_templates',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('output_schema', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_prompt_template_version')
    )
    op.create_table('onboarding_plans',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('job_role_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('verification_status', sa.String(length=40), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('prompt_template_id', sa.UUID(), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_document_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('excluded_chunks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], ),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_plans_employee_id'), 'onboarding_plans', ['employee_id'], unique=False)
    op.create_index(op.f('ix_onboarding_plans_is_current'), 'onboarding_plans', ['is_current'], unique=False)
    op.create_index(op.f('ix_onboarding_plans_job_role_id'), 'onboarding_plans', ['job_role_id'], unique=False)
    op.create_index(op.f('ix_onboarding_plans_status'), 'onboarding_plans', ['status'], unique=False)
    op.create_index(op.f('ix_onboarding_plans_verification_status'), 'onboarding_plans', ['verification_status'], unique=False)
    op.create_table('generation_runs',
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('prompt_template_version', sa.String(length=60), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('attempts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_request', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['onboarding_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_runs_employee_id'), 'generation_runs', ['employee_id'], unique=False)
    op.create_index(op.f('ix_generation_runs_plan_id'), 'generation_runs', ['plan_id'], unique=False)
    op.create_table('plan_modules',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=150), nullable=True),
    sa.Column('competency', sa.String(length=150), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('learning_objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('key_concepts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_source_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('learning_activities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assessment_summary', sa.Text(), nullable=True),
    sa.Column('completion_criteria', sa.Text(), nullable=True),
    sa.Column('requirement_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scenarios', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('regeneration_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('requirement_code', sa.String(length=20), nullable=True),
    sa.Column('source_document_id', sa.String(length=64), nullable=True),
    sa.Column('source_section_id', sa.String(length=40), nullable=True),
    sa.Column('source_chunk_code', sa.String(length=60), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.String(length=12), nullable=True),
    sa.Column('due_stage', sa.String(length=30), nullable=True),
    sa.Column('completion_status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_outdated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['onboarding_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_modules_plan_id'), 'plan_modules', ['plan_id'], unique=False)
    op.create_index(op.f('ix_plan_modules_requirement_code'), 'plan_modules', ['requirement_code'], unique=False)
    op.create_table('assessments',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('assessment_type', sa.String(length=40), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('passing_score', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('requirement_code', sa.String(length=20), nullable=True),
    sa.Column('source_document_id', sa.String(length=64), nullable=True),
    sa.Column('source_section_id', sa.String(length=40), nullable=True),
    sa.Column('source_chunk_code', sa.String(length=60), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.String(length=12), nullable=True),
    sa.Column('due_stage', sa.String(length=30), nullable=True),
    sa.Column('completion_status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_outdated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['plan_modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['onboarding_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_module_id'), 'assessments', ['module_id'], unique=False)
    op.create_index(op.f('ix_assessments_plan_id'), 'assessments', ['plan_id'], unique=False)
    op.create_index(op.f('ix_assessments_requirement_code'), 'assessments', ['requirement_code'], unique=False)
    op.create_table('checklist_items',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('activity', sa.Text(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('responsible_person', sa.String(length=80), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('requirement_code', sa.String(length=20), nullable=True),
    sa.Column('source_document_id', sa.String(length=64), nullable=True),
    sa.Column('source_section_id', sa.String(length=40), nullable=True),
    sa.Column('source_chunk_code', sa.String(length=60), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.String(length=12), nullable=True),
    sa.Column('due_stage', sa.String(length=30), nullable=True),
    sa.Column('completion_status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_outdated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['plan_modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['onboarding_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_items_module_id'), 'checklist_items', ['module_id'], unique=False)
    op.create_index(op.f('ix_checklist_items_plan_id'), 'checklist_items', ['plan_id'], unique=False)
    op.create_index(op.f('ix_checklist_items_requirement_code'), 'checklist_items', ['requirement_code'], unique=False)
    op.create_table('plan_tasks',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('expected_outcome', sa.Text(), nullable=True),
    sa.Column('completion_criteria', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('requirement_code', sa.String(length=20), nullable=True),
    sa.Column('source_document_id', sa.String(length=64), nullable=True),
    sa.Column('source_section_id', sa.String(length=40), nullable=True),
    sa.Column('source_chunk_code', sa.String(length=60), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.String(length=12), nullable=True),
    sa.Column('due_stage', sa.String(length=30), nullable=True),
    sa.Column('completion_status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_outdated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['plan_modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['onboarding_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_tasks_module_id'), 'plan_tasks', ['module_id'], unique=False)
    op.create_index(op.f('ix_plan_tasks_plan_id'), 'plan_tasks', ['plan_id'], unique=False)
    op.create_index(op.f('ix_plan_tasks_requirement_code'), 'plan_tasks', ['requirement_code'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('question_type', sa.String(length=40), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('is_outdated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('requirement_code', sa.String(length=20), nullable=True),
    sa.Column('source_document_id', sa.String(length=64), nullable=True),
    sa.Column('source_section_id', sa.String(length=40), nullable=True),
    sa.Column('source_chunk_code', sa.String(length=60), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.String(length=12), nullable=True),
    sa.Column('due_stage', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['plan_modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['onboarding_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_questions_module_id'), 'quiz_questions', ['module_id'], unique=False)
    op.create_index(op.f('ix_quiz_questions_plan_id'), 'quiz_questions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_quiz_questions_requirement_code'), 'quiz_questions', ['requirement_code'], unique=False)
    op.create_table('assessment_rubric_criteria',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('criterion', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('expected_performance', sa.Text(), nullable=False),
    sa.Column('pass_condition', sa.Text(), nullable=False),
    sa.Column('requirement_code', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_rubric_criteria_assessment_id'), 'assessment_rubric_criteria', ['assessment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_rubric_criteria_assessment_id'), table_name='assessment_rubric_criteria')
    op.drop_table('assessment_rubric_criteria')
    op.drop_index(op.f('ix_quiz_questions_requirement_code'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_plan_id'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_module_id'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_plan_tasks_requirement_code'), table_name='plan_tasks')
    op.drop_index(op.f('ix_plan_tasks_plan_id'), table_name='plan_tasks')
    op.drop_index(op.f('ix_plan_tasks_module_id'), table_name='plan_tasks')
    op.drop_table('plan_tasks')
    op.drop_index(op.f('ix_checklist_items_requirement_code'), table_name='checklist_items')
    op.drop_index(op.f('ix_checklist_items_plan_id'), table_name='checklist_items')
    op.drop_index(op.f('ix_checklist_items_module_id'), table_name='checklist_items')
    op.drop_table('checklist_items')
    op.drop_index(op.f('ix_assessments_requirement_code'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_plan_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_module_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_plan_modules_requirement_code'), table_name='plan_modules')
    op.drop_index(op.f('ix_plan_modules_plan_id'), table_name='plan_modules')
    op.drop_table('plan_modules')
    op.drop_index(op.f('ix_generation_runs_plan_id'), table_name='generation_runs')
    op.drop_index(op.f('ix_generation_runs_employee_id'), table_name='generation_runs')
    op.drop_table('generation_runs')
    op.drop_index(op.f('ix_onboarding_plans_verification_status'), table_name='onboarding_plans')
    op.drop_index(op.f('ix_onboarding_plans_status'), table_name='onboarding_plans')
    op.drop_index(op.f('ix_onboarding_plans_job_role_id'), table_name='onboarding_plans')
    op.drop_index(op.f('ix_onboarding_plans_is_current'), table_name='onboarding_plans')
    op.drop_index(op.f('ix_onboarding_plans_employee_id'), table_name='onboarding_plans')
    op.drop_table('onboarding_plans')
    op.drop_table('prompt_templates')
    # ### end Alembic commands ###
