"""requirement precedence override

Revision ID: 5f09fedc19d7
Revises: 8969f7904a4d
Create Date: 2026-09-23 21:44:44.162427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f09fedc19d7'
down_revision: Union[str, Sequence[str], None] = '8969f7904a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirements', sa.Column('overridden_by', sa.String(length=20), nullable=True))
    op.add_column('requirements', sa.Column('override_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirements', 'override_reason')
    op.drop_column('requirements', 'overridden_by')
    # ### end Alembic commands ###
