"""impact records

Revision ID: 8969f7904a4d
Revises: ed0d3dc0a4b6
Create Date: 2026-09-23 21:01:20.028748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8969f7904a4d'
down_revision: Union[str, Sequence[str], None] = 'ed0d3dc0a4b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impact_records',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('previous_document_id', sa.UUID(), nullable=True),
    sa.Column('document_code', sa.String(length=60), nullable=False),
    sa.Column('previous_version', sa.Integer(), nullable=True),
    sa.Column('new_version', sa.Integer(), nullable=False),
    sa.Column('changed_sections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('affected_requirement_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('affected_requirement_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('affected_item_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reference_only_item_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('affected_plan_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('affected_employee_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('regeneration_status', sa.String(length=20), nullable=False),
    sa.Column('regeneration_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['previous_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impact_records_document_code'), 'impact_records', ['document_code'], unique=False)
    op.create_index(op.f('ix_impact_records_document_id'), 'impact_records', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_impact_records_document_id'), table_name='impact_records')
    op.drop_index(op.f('ix_impact_records_document_code'), table_name='impact_records')
    op.drop_table('impact_records')
    # ### end Alembic commands ###
