"""progress quiz attempts assessment results

Revision ID: ed0d3dc0a4b6
Revises: 264848d03e0a
Create Date: 2026-09-23 20:59:20.592295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed0d3dc0a4b6'
down_revision: Union[str, Sequence[str], None] = '264848d03e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_results',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=True),
    sa.Column('competency', sa.String(length=150), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('assessor_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('criteria_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assessor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['onboarding_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_results_assessment_id'), 'assessment_results', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_results_employee_id'), 'assessment_results', ['employee_id'], unique=False)
    op.create_index(op.f('ix_assessment_results_plan_id'), 'assessment_results', ['plan_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('requirement_code', sa.String(length=20), nullable=True),
    sa.Column('competency', sa.String(length=150), nullable=True),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['onboarding_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_competency'), 'quiz_attempts', ['competency'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_employee_id'), 'quiz_attempts', ['employee_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_plan_id'), 'quiz_attempts', ['plan_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_question_id'), 'quiz_attempts', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_attempts_question_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_plan_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_employee_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_competency'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_assessment_results_plan_id'), table_name='assessment_results')
    op.drop_index(op.f('ix_assessment_results_employee_id'), table_name='assessment_results')
    op.drop_index(op.f('ix_assessment_results_assessment_id'), table_name='assessment_results')
    op.drop_table('assessment_results')
    # ### end Alembic commands ###
