import enum


class UserType(str, enum.Enum):
    ADMIN = "ADMIN"
    TRAINING_MANAGER = "TRAINING_MANAGER"
    REVIEWER = "REVIEWER"
    MANAGER = "MANAGER"
    EMPLOYEE = "EMPLOYEE"


class ExperienceLevel(str, enum.Enum):
    BEGINNER = "BEGINNER"
    INTERMEDIATE = "INTERMEDIATE"
    ADVANCED = "ADVANCED"


class TrainingStatus(str, enum.Enum):
    NOT_STARTED = "NOT_STARTED"
    IN_PROGRESS = "IN_PROGRESS"
    ON_TRACK = "ON_TRACK"
    REQUIRES_ATTENTION = "REQUIRES_ATTENTION"
    BEHIND_SCHEDULE = "BEHIND_SCHEDULE"
    ASSESSMENT_REQUIRED = "ASSESSMENT_REQUIRED"
    COMPLETED = "COMPLETED"

class DocumentType(str, enum.Enum):
    HANDBOOK = "HANDBOOK"
    HR_POLICY = "HR_POLICY"
    LEAVE_POLICY = "LEAVE_POLICY"
    INFOSEC_POLICY = "INFOSEC_POLICY"
    CONDUCT_POLICY = "CONDUCT_POLICY"
    DATA_PRIVACY_POLICY = "DATA_PRIVACY_POLICY"
    DEPARTMENT_SOP = "DEPARTMENT_SOP"
    ROLE_DESCRIPTION = "ROLE_DESCRIPTION"
    PROCESS_DOCUMENT = "PROCESS_DOCUMENT"
    FAQ = "FAQ"
    COMPLIANCE_INSTRUCTION = "COMPLIANCE_INSTRUCTION"
    ESCALATION_PROCEDURE = "ESCALATION_PROCEDURE"


class DocumentStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    OBSOLETE = "OBSOLETE"
    EXPIRED = "EXPIRED"
    QUARANTINED = "QUARANTINED"

class RequirementType(str, enum.Enum):
    """SRS Step 11."""
    MUST_KNOW = "MUST_KNOW"
    MUST_COMPLETE = "MUST_COMPLETE"
    MUST_DEMONSTRATE = "MUST_DEMONSTRATE"
    MUST_ACKNOWLEDGE = "MUST_ACKNOWLEDGE"
    RECOMMENDED = "RECOMMENDED"
    OPTIONAL = "OPTIONAL"
    NOT_APPLICABLE = "NOT_APPLICABLE"


MANDATORY_TYPES = {
    RequirementType.MUST_KNOW,
    RequirementType.MUST_COMPLETE,
    RequirementType.MUST_DEMONSTRATE,
    RequirementType.MUST_ACKNOWLEDGE,
}


class Priority(str, enum.Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


PRIORITY_ORDER = {Priority.CRITICAL: 0, Priority.HIGH: 1, Priority.MEDIUM: 2, Priority.LOW: 3}


class MappingMethod(str, enum.Enum):
    EXPLICIT_ROLE_MENTION = "EXPLICIT_ROLE_MENTION"
    DEPARTMENT_MATCH = "DEPARTMENT_MATCH"
    APPLIES_TO_ALL = "APPLIES_TO_ALL"
    MANUAL = "MANUAL"
